version: '3.1'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - app-network
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: laravel
            DB_USERNAME: laravel
            DB_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            -   db

    db:
        image: mysql:8
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        volumes:
            - ./data:/var/lib/mysql
        networks:
            - app-network

networks:
    app-network:
